[package]
name = "tensor"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies.kindle-burn]
path = "../../"
version = "0.1.0"
features = ["std", "wgpu", "fusion", "candle", "ndarray"]

[dependencies]
